### PR TITLE
Adding support for boost::filesystem

### LINKED ISSUE #91: Allow boost::filesystem for macOS compatibility?
I've started to use url and like it quite a lot. However I've hit a blocker problem in that Apple introduced full support for std::filesystem only in macOS 10.15, which very much limits the applicability of url. If I can propose optional support for boost::filesystem, would that be an acceptable merge request?

### PR DESCRIPTION
**Pull request by emmenlau**
Closes #91

### CODE REVIEW

**Comment by emmenlau** [comment]
The error in https://travis-ci.org/github/cpp-netlib/url/jobs/684389885 is unrelated. However please see #91 before merging to discuss the proper integration of `std::filesystem::path::generic_u8string()`.

**Comment by glynos** [comment]
Thanks for the fast fix.

I'm wondering if it's not better just to treat std::filesystem::path, std::experimental::path and boost::filesystem::path as 3 different overloads, instead of redefining with macros. What would be easiest for someone who was migrating from one to another?

**Comment by glynos** [comment]
> The error in https://travis-ci.org/github/cpp-netlib/url/jobs/684389885 is unrelated. However please see #91 before merging to discuss the proper integration of `std::filesystem::path::generic_u8string()`.

It's a Travis thing, so I restarted the job.

**Comment by glynos** [comment]
> Thanks for the fast fix.
> 
> I'm wondering if it's not better just to treat std::filesystem::path, std::experimental::path and boost::filesystem::path as 3 different overloads, instead of redefining with macros. What would be easiest for someone who was migrating from one to another?

Yeah, I would like to think the macro trick was useful if you were just to upgrade your compiler. However, Boost is a different dependency and I would prefer to treat that differently.

Perhaps I would like to keep the std::experimental::filesystem/std::filesystem test, but put the functions that use boost filesystem in a different namespace (skyr::boost::filesystem?)

**Comment by emmenlau** [comment]
> > I'm wondering if it's not better just to treat std::filesystem::path, std::experimental::path and boost::filesystem::path as 3 different overloads, instead of redefining with macros. What would be easiest for someone who was migrating from one to another?
> 
> Yeah, I would like to think the macro trick was useful if you were just to upgrade your compiler. However, Boost is a different dependency and I would prefer to treat that differently.
> 
> Perhaps I would like to keep the std::experimental::filesystem/std::filesystem test, but put the functions that use boost filesystem in a different namespace (skyr::boost::filesystem?)

I would put my word in for the current solution :-) Since std::filesystem is really just derived from boost::filesystem (and has been standardized with very little changes), I would think it fair to treat them as largely compatible implementations. This seems also less intrusive to your code?
Or do you see it differently?

**Comment by glynos** [comment]
I'm thinking of another team working in a mixed environment in a different situation to yours, where (for whatever reason) they can't quite fully migrate from Boost.Filesystem to C++17 filesystem, or are some mix of the two.

I'm not sure, I'll give it a bit more thought.

**Comment by glynos** [comment]
As for the use of generic_string: it's not so straightforward as I see it. Boost.Filesystem uses a default argument of a std::codecvt:

https://www.boost.org/doc/libs/1_70_0/libs/filesystem/doc/reference.html#generic_string-template

See also:

https://en.cppreference.com/w/cpp/locale/codecvt_utf8

So the equivalent behaviour should be:

```
return make_url("file://" + path.generic_string(std::codecvt_utf8())); 
```

**Comment by emmenlau** [comment]
> As for the use of generic_string: it's not so straightforward as I see it. Boost.Filesystem uses a default argument of a std::codecvt:

I see. But would your unicode-handlers be able to transparently wrap `path.generic_string()` with a matching conversion? Something like this that could work for all filesystem implementations?
```
unicode::as<std::string>(path.generic_string() | unicode::transform::to_u8)
```

**Comment by glynos** [comment]
Based on [this comment](https://github.com/cpp-netlib/url/issues/91#issuecomment-625657467), considering Boost.Filesystem as a drop-in replacement isn't as straightforward as we'd hope.

If this library is going to have an optional dependency on Boost, I'd rather make that explicit.

So move that Boost.Filesystem to <skyr/boost/filesystem/path.hpp>

**Comment by emmenlau** [comment]
Ok I can do that! But can you help me understand how you want the syntax? How would `include/skyr/v1/filesystem/path.hpp` look like after your proposed change? It still needs to know whether to call boost or std, or not?

Or would `skyr/boost/filesystem/path.hpp` be a full drop-in replacement for `include/skyr/v1/filesystem/path.hpp`? But that might duplicate code?

**Comment by glynos** [comment]
I think I prefer the second option for now. I think it's not exactly duplicate code (the call to generic_string or u8generic_string being the most important part). And it can be refactored later.

Talking about refactoring, the new function needs to have at least one unit test.

Thanks again for your input.

**Comment by glynos** [comment]
Hello @emmenlau,

What is your plan with this PR? Be aware I made some recent changes to the CMakeLists.txt that may affect your changes.

**Comment by glynos** [comment]
Hi, I updated the name of the default branch and closed the 'master' branch, which closed this PR. It didn't have any activity anyway, so let me know if you still want me to merge an update.

**Pull request closed without merging**
